---
abstract: 'Generic traversal of distributions in a CPAN repository'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Spec: 3.29
  Test::More: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Visitor
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
provides:
  CPAN::Visitor:
    file: lib/CPAN/Visitor.pm
    version: 0.001
requires:
  Archive::Extract: 0.34
  File::Find: 0
  File::Temp: 0.2
  File::pushd: 1
  Moose: 0.93
  MooseX::Params::Validate: 0.13
  Parallel::ForkManager: 0.007005
  Path::Class: 0.17
  autodie: 0
  namespace::autoclean: 0.09
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=CPAN-Visitor
  repository: http://github.com/dagolden/CPAN-Visitor/
version: 0.001
