---
abstract: 'Generic traversal of distributions in a CPAN repository'
author:
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120630'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Visitor
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Visitor:
    file: lib/CPAN/Visitor.pm
    version: 0.003
requires:
  Archive::Extract: 0.34
  File::Find: 0
  File::Temp: 0.20
  File::pushd: 1.00
  Moose: 0.93
  MooseX::Params::Validate: 0.13
  Parallel::ForkManager: 0.007005
  Path::Class: 0.17
  autodie: 0
  namespace::autoclean: 0.09
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Visitor
  homepage: https://github.com/dagolden/cpan-visitor
  repository: https://github.com/dagolden/cpan-visitor.git
version: 0.003
